services:
  openwebrx:
    image: ghcr.io/sergey125/openwebrx-masterru:latest
    pull_policy: always
    container_name: openwebrx
    restart: unless-stopped
    ports:
      - "8073:8073"
    volumes:
      - openwebrx-settings:/var/lib/openwebrx
      - openwebrx-etc:/etc/openwebrx

volumes:
  openwebrx-settings:
  openwebrx-etc:
